# Site settings
title: Michael Gilardi
description: Senior Software Engineer | Salesforce Developer | Michael Gilardi
baseurl: "" # the subpath of your site, e.g. /blog
domain: "http://mgilardi.github.io" # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: "http://mgilardi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# User settings
username: Michael Gilardi
user_description_title: My MO
user_description: Michael Gilardi is a full stack software engineer specializing in Salesforce development. In his spare time, he enjoys exploring extraneous technological rabbit holes.
user_title: Senior Software Engineer
linkedin_username: mdgilardi
github_username:  mgilardi
salesforce_username: mgilardi
asu_profile_urL: search.asu.edu/profile/1467777
business_name: Cyber Sonoran
business_url: cybersonoran.com

exclude: ['package.json', 'src', 'node_modules', 'vendor']

